### ISSUE TITLE
array lengths can't depend on generic parameters

### ISSUE THREAD

**Issue by tonis2** [adrien-ben/gltf-viewer-rs#17]
![error](https://user-images.githubusercontent.com/9265556/72818494-3fa6f280-3c74-11ea-9b09-2de7f79a133c.png)

I am getting error about generic array lengths, when running on `Ubuntu 18.04.3 LTS`, 

Did not find any solution when googling, any ideas ?

Thanks

**Comment by adrien-ben** [comment]
Hi, 

from what I see in the screenshot it looks like a problem with proc-macro2. What toolchain are you using ?

**Comment by tonis2** [comment]
The error went away when, i updated to cargo version to `1.42.0-nightly`
